### PR TITLE
Filter transfers by orderId

### PR DESCRIPTION
**Pull request by daniL16**
Get Stripe transfers for an given miraklId

### CODE REVIEW

**Comment by youssef-stripe** [comment]
Hi @daniL16,

Thanks for the contribution!

I'd recommend adding an item to the `itemOperations` so users can discover this parameter in the generated API specs:
```
 *      itemOperations={
 *          "get"={"path"="/transfers?miraklId={id}"},
 *          "get"={"path"="/transfers/{id}", "requirements"={"id"="\d+"}},
 *      },
```

Result:
image

What do you think?

**Comment by daniL16** [comment]
It is another option, but I prefer to do it through the ApiFilters. In this way it is easier to add new filters if necessary

**Comment by youssef-stripe** [comment]
This is fine. Note that you can use both in the future, i.e. ApiFilters for the actual endpoint and itemOperations under ApiResource for the specs.

I'll merge for now. Feel free to create a new PR should you want to add anything else.

**Comment by youssef-stripe** [comment]
Last note, we are planning a new release a few weeks from now. Do you need a release for this change or can this wait our next planned release?

**Comment by daniL16** [comment]
> Last note, we are planning a new release a few weeks from now. Do you need a release for this change or can this wait our next planned release?


We don't mind waiting for the next version. Thanks for the attention

**Pull request merged**
